### ISSUE TITLE
不回答弹幕呢？

### ISSUE THREAD

**Issue by yangyuan-zhen** [jiran214/GPT-vup#26]
![f84d32c13b82827146485988ec93da1](https://github.com/jiran214/GPT-vup/assets/82722641/cc3a6a89-658c-451a-8b2f-633905267b70)
就一直这样

**Comment by yangyuan-zhen** [comment]
搞定了

**Comment by SherlockSunset** [comment]
> 搞定了

请问是怎么解决这个问题的呀
